### ISSUE TITLE
Fatal bug: Some websites crashes completely

### ISSUE THREAD

**Issue by michaelmcmillan** [michaelmcmillan/LittList#76]
https://slettmeg.no/om-oss

**Comment by michaelmcmillan** [comment]
``` json
{"date":"Sun May 03 2015 12:58:48 GMT-0400 (EDT)","process":{"pid":16741,"uid":1000,"gid":1000,"cwd":"/srv/beta.littlist.no","execPath":"/usr/bin/iojs","version":"v1.2.0","argv":["iojs","/srv/beta.littlist.no/web/server.js"],"memoryUsage":{"rss":75931648,"heapTotal":63773184,"heapUsed":44470288}},"os":{"loadavg":[0.10546875,0.08642578125,0.0625],"uptime":857064},"trace":[{"column":11,"file":"url.js","function":"Url.parse","line":90,"method":"parse","native":false},{"column":5,"file":"url.js","function":"Object.urlParse [as parse]","line":84,"method":"urlParse [as parse]","native":false},{"column":34,"file":"/srv/beta.littlist.no/models/website.js","function":"Website.getHostname","line":16,"method":"getHostname","native":false},{"column":25,"file":"/srv/beta.littlist.no/models/website.js","function":"Website.getTitle","line":69,"method":"getTitle","native":false},{"column":41,"file":"/srv/beta.littlist.no/database/factories/website.js","function":"Object.WebsiteFactory.create","line":38,"method":"WebsiteFactory.create","native":false},{"column":32,"file":"/srv/beta.littlist.no/controllers/query/readability.js","function":null,"line":34,"method":null,"native":false},{"column":13,"file":"/srv/beta.littlist.no/parsers/readability/readability.js","function":"Request._callback","line":87,"method":"_callback","native":false},{"column":22,"file":"/srv/beta.littlist.no/node_modules/request/request.js","function":"Request.self.callback","line":368,"method":"self.callback","native":false},{"column":13,"file":"events.js","function":"emitTwo","line":85,"method":null,"native":false},{"column":7,"file":"events.js","function":"Request.emit","line":153,"method":"emit","native":false}],"stack":["TypeError: Parameter 'url' must be a string, not undefined","    at Url.parse (url.js:90:11)","    at Object.urlParse [as parse] (url.js:84:5)","    at Website.getHostname (/srv/beta.littlist.no/models/website.js:16:34)","    at Website.getTitle (/srv/beta.littlist.no/models/website.js:69:25)","    at Object.WebsiteFactory.create (/srv/beta.littlist.no/database/factories/website.js:38:41)","    at /srv/beta.littlist.no/controllers/query/readability.js:34:32","    at Request._callback (/srv/beta.littlist.no/parsers/readability/readability.js:87:13)","    at Request.self.callback (/srv/beta.littlist.no/node_modules/request/request.js:368:22)","    at emitTwo (events.js:85:13)","    at Request.emit (events.js:153:7)"],"level":"error","message":"uncaughtException: Parameter 'url' must be a string, not undefined","timestamp":"2015-05-03T16:58:48.336Z"}
{"level":"info","message":"LittList is now listening on port 8080","timestamp":"2015-05-03T16:58:49.836Z"}
```
